# to get windows' class-name use
# $ hyprctl clients | grep -i class
[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "shift_monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]


# [monitors]
# unknown = "wlrlui"

[monitors.placement]
"Samsung".leftOf = "HDMI-A-1"
"California".rightOf = "eDP-1"

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "50% 75%"
unfocus = "hide"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"

[scratchpads.term-mc]
animation = "fromTop"
command = "kitty --class kitty-dropterm-mc mc"
class = "kitty-dropterm-mc"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"

[scratchpads.term-debugger]
animation = "fromTop"
command = "kitty --class kitty-dropterm-debugger screen /dev/ttyUSB0 1500000"
class = "kitty-dropterm-debugger"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"

[scratchpads.term-nmtui]
animation = "fromRight"
command = "kitty --class kitty-dropterm-nmtui nmtui"
class = "kitty-dropterm-nmtui"
lazy = true
size = "19% 35%"
unfocus = "hide"

[scratchpads.bluetooth]
animation = "fromRight"
command = "blueman-manager"
class = ".blueman-manager-wrapped"
lazy = true
size = "19% 35%"
unfocus = "hide"

[scratchpads.nixpkgs-search]
animation = "fromTop"
command = "firefox --no-remote --class nixpkgs-search --new-window https://search.nixos.org/packages"
# class = "nixpkgs-search"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"

[scratchpads.discord]
animation = "fromTop"
command = "discord"
class = "discord"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"

[scratchpads.emacs]
animation = "fromTop"
command = "emacs"
class = "Emacs"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"

[scratchpads.obs-studio]
animation = "fromTop"
command = "obs"
class = "com.obsproject.Studio"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"


# [scratchpads.spotify]
# animation = "fromTop"
# command = "spotifywm"
# class = "spotify"
# size = "50% 75%"
# position = "25% 5%"
# excludes = "*"
