[[bars]]
monitor = "DP-1"
position = "top"
height = 28

start = [
  { type = "workspaces" },
]

center = [
  { type = "clock", format = "%A | %r | %m-%d-%Y" },
  { type = "label", label = "|" },
  { type = "script", cmd = "$HOME/.config/ironbar/scripts/weather.sh", mode = "poll", interval = 300 },
]

end = [
  { type = "script", name = "privacy", cmd = "$HOME/.config/ironbar/scripts/privacy.sh", mode = "poll", interval = 1000 },
  { type = "label", label = "|" },
  { type = "network_manager" },
  { type = "label", label = "|" },
  { type = "volume", format = "{icon} {percentage}%", max_volume = 100 },
  { type = "label", label = "|" },
  { type = "script", name = "audio-viz", cmd = "$HOME/.config/ironbar/scripts/audio-viz.sh", mode = "poll", interval = 200 },
  { type = "label", label = "|" },
  { type = "battery", format = "{icon} {percentage}%" },
  { type = "label", label = "|" },
  { type = "tray", icon_size = 24 },
]

[[bars]]
monitor = "DP-1"
position = "bottom"
height = 28

start = [
  { type = "label", label = "|" },
  { type = "script", name = "disk-boot", cmd = "df -h /boot | awk 'NR==2 {print \" /boot \" $5}'", mode = "poll", interval = 5000 },
  { type = "label", label = "|" },
  { type = "script", name = "disk-nix", cmd = "df -h /nix | awk 'NR==2 {print \" /nix \" $5}'", mode = "poll", interval = 5000 },
  { type = "label", label = "|" },
  { type = "script", name = "memory", cmd = "$HOME/.config/ironbar/scripts/memory.sh", mode = "poll", interval = 5000 },
  { type = "label", label = "|" },
  { type = "script", name = "cpu", cmd = "$HOME/.config/ironbar/scripts/cpu.sh", mode = "poll", interval = 1000 },
  { type = "label", label = "|" },
  { type = "script", name = "temperature", cmd = "$HOME/.config/ironbar/scripts/temperature.sh", mode = "poll", interval = 5000 },
]

center = []
end = []
