#!/usr/bin/env bash
# CPU usage from /proc/stat (two samples, 1s apart)
read_cpu() {
    awk '/^cpu /{print $2, $3, $4, $5, $6, $7, $8}' /proc/stat
}
read -r u1 n1 s1 i1 w1 q1 sq1 <<< "$(read_cpu)"
sleep 1
read -r u2 n2 s2 i2 w2 q2 sq2 <<< "$(read_cpu)"
idle_d=$((i2 - i1))
total_d=$(( (u2+n2+s2+i2+w2+q2+sq2) - (u1+n1+s1+i1+w1+q1+sq1) ))
if [ "$total_d" -gt 0 ]; then
    echo $(( (total_d - idle_d) * 100 / total_d ))
else
    echo 0
fi
