{ config, lib, ... }:
with lib;
let
  cfg = config.stylix.targets.lsd;
  colors = config.lib.stylix.colors;
  # hasHomeManager = config ? home-manager && config.home-manager ? users;

  # Function to map Stylix colors to Xterm 256 colors
  toXtermColor = {
    base05 = 230; # Light grey
    base0B = 28; # Dark green
    base0A = 136; # Dark yellow
    base08 = 88; # Dark red
    base0E = 200; # Magenta (closest)
    base03 = 245; # Dark grey
    base0D = 44; # Dark cyan
    base06 = 51; # Cyan (closest)
    base0C = 36; # Light green (closest)
    base04 = 36; # Beige (closest)
    base0F = 131; # Pink (closest)
  };

in
{
  options.stylix.targets.lsd = {
    enable = config.lib.stylix.mkEnableTarget "lsd" true;
  };

  config = mkIf (config.stylix.enable && cfg.enable) {
    # Create the colors.yaml file in /etc
    environment.etc."lsd/colors.yaml" = {
      text = ''
        # Generated by Stylix

        # Main elements
        user: "230"
        group: "230"
        permission:
          read: "${toXtermColor.base0B}"
          write: "${toXtermColor.base0A}"
          exec: "${toXtermColor.base08}"
          exec-sticky: "5"
          no-access: "${toXtermColor.base03}"
          octal: "6"
          acl: "${toXtermColor.base0D}"
          context: "${toXtermColor.base06}"
        date:
          hour-old: "${toXtermColor.base0D}"
          day-old: "${toXtermColor.base0C}"
          older: "${toXtermColor.base04}"
        size:
          none: "${toXtermColor.base03}"
          small: "${toXtermColor.base0B}"
          medium: "${toXtermColor.base0A}"
          large: "${toXtermColor.base08}"
        inode:
          valid: "${toXtermColor.base0D}"
          invalid: "${toXtermColor.base03}"
        links:
          valid: "${toXtermColor.base0B}"
          invalid: "${toXtermColor.base08}"
        tree-edge: "${toXtermColor.base03}"

        # Git status
        git-status:
          default: "${toXtermColor.base03}"
          unmodified: "${toXtermColor.base03}"
          ignored: "${toXtermColor.base03}"
          new-in-index: "${toXtermColor.base0B}"
          new-in-workdir: "${toXtermColor.base0B}"
          typechange: "${toXtermColor.base0A}"
          deleted: "${toXtermColor.base08}"
          renamed: "${toXtermColor.base0B}"
          modified: "${toXtermColor.base0A}"
          conflicted: "${toXtermColor.base08}"

        # Special files
        character-device: "${toXtermColor.base0E}"
        block-device: "${toXtermColor.base0D}"
        fifo: "${toXtermColor.base0C}"
        socket: "${toXtermColor.base0F}"
        symlink: "${toXtermColor.base0D}"
        broken-symlink: "${toXtermColor.base08}"

        # Directory and files
        directory-header: "230"
        directory: "${toXtermColor.base0D}"
        filetype:
          binary: "${toXtermColor.base0F}"
          text: "${toXtermColor.base0B}"
          multimedia: "${toXtermColor.base0E}"
          documents: "${toXtermColor.base0D}"
          data: "${toXtermColor.base0C}"
          compressed: "${toXtermColor.base0F}"
          executable: "${toXtermColor.base08}"
          
        # Headers and special text
        header: "${toXtermColor.base0E}"
        name: "230"
      '';
    };

    # Create a symlink in user's home directory
    system.userActivationScripts.stylixLsd = ''
      mkdir -p $HOME/.config/lsd
      ln -sf /etc/lsd/colors.yaml $HOME/.config/lsd/colors.yaml

      # Make sure permissions are correct
      chmod 644 $HOME/.config/lsd/colors.yaml
    '';

    # Set the theme to "custom" in all home-manager users
    home-manager.sharedModules = [
      {
        programs.lsd.settings.color = {
          theme = "custom";
          when = "auto"; # Ensure colors are enabled
        };
      }
    ];
  };
}
