# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running 'nixos-help').

{ config, pkgs, lib, ... }:

{
  imports = [
    ../skyspy-dev/persistence.nix
  ];

  # Thunderbolt support
  services.hardware.bolt.enable = true;

  # Kernel and memory optimizations (from yoga)
  boot.kernel.sysctl = {
    # Network optimizations - BBR congestion control
    "net.core.default_qdisc" = "fq";
    "net.ipv4.tcp_congestion_control" = "bbr";

    # Security inode enhancements
    "fs.inotify.max_user_watches" = 524288;
    "fs.inotify.max_queued_events" = 524288;

    # I/O and memory optimizations
    "vm.swappiness" = 1;
    "vm.vfs_cache_pressure" = 50;
    "vm.dirty_background_ratio" = 3;
    "vm.dirty_ratio" = 8;
    "vm.transparent_hugepage" = "madvise";
    "vm.max_map_count" = 262144;
  };

  # Graphics and Nvidia configuration handled by common nvidia module

  networking.wireless.enable = false;

  # Security and audit - comprehensive logging
  security.auditd.enable = true;
  security.audit.enable = true;
  security.audit.rules = [
    # Root executions (all architectures)
    "-a exit,always -F arch=b64 -F euid=0 -S execve -k root_commands"
    "-a exit,always -F arch=b32 -F euid=0 -S execve -k root_commands"
    
    # All user executions (comprehensive process monitoring)
    "-a exit,always -F arch=b64 -S execve -k user_commands"
    "-a exit,always -F arch=b32 -S execve -k user_commands"
    
    # File modifications and deletions (not all opens - too noisy)
    "-a exit,always -F arch=b64 -S unlink,unlinkat,rename,renameat,rmdir,truncate,ftruncate -k file_deletion"
    "-a exit,always -F arch=b32 -S unlink,unlinkat,rename,renameat,rmdir,truncate,ftruncate -k file_deletion"
    
    # Permission changes
    "-a exit,always -F arch=b64 -S chmod,fchmod,fchmodat,chown,fchown,fchownat,setxattr,lsetxattr,fsetxattr -k perm_mod"
    "-a exit,always -F arch=b32 -S chmod,fchmod,fchmodat,chown,fchown,fchownat,setxattr,lsetxattr,fsetxattr -k perm_mod"
    
    # Module loading
    "-a exit,always -F arch=b64 -S init_module,finit_module,delete_module -k modules"
    "-a exit,always -F arch=b32 -S init_module,finit_module,delete_module -k modules"
    
    # System time changes
    "-a exit,always -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time_change"
    "-a exit,always -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time_change"
    
    # Mount operations
    "-a exit,always -F arch=b64 -S mount,umount2 -k mount"
    "-a exit,always -F arch=b32 -S mount,umount2 -k mount"
    
    # User/group changes (only files that exist on NixOS)
    "-w /etc/passwd -p wa -k identity"
    "-w /etc/group -p wa -k identity"
    "-w /etc/shadow -p wa -k identity"
    
    # Sudoers file changes
    "-w /etc/sudoers -p wa -k sudoers"
    "-w /etc/sudoers.d/ -p wa -k sudoers"
    
    # System configuration (NixOS specific)
    "-w /etc/nixos/ -p wa -k nixos_config"
    "-w /boot/ -p wa -k boot"
    
    # Login/logout events (only existing files)
    "-w /var/log/lastlog -p wa -k logins"
    
    # Session events
    "-w /var/run/utmp -p wa -k session"
    "-w /var/log/wtmp -p wa -k session"
    "-w /var/log/btmp -p wa -k session"
    
    # Make configuration immutable (must be last)
    # Once set, audit rules cannot be changed until reboot (security best practice)
    "-e 2"
  ];
  
  # Disable filter plugin to avoid "line too long" error
  # The filter.conf generated by NixOS has an excessively long args line
  # This doesn't affect audit functionality - just the optional dispatcher
  environment.etc."audit/plugins.d/filter.conf".text = lib.mkForce ''
    active = no
  '';

  security.sudo.extraConfig = ''
    Defaults timestamp_timeout=0
    Defaults !tty_tickets
    Defaults log_output
    Defaults log_input
    Defaults logfile=/var/log/sudo.log
  '';

  networking.networkmanager.enable = true;

  time.timeZone = "America/Denver";
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable CUPS to print documents.
  # services.printing.enable = true; # Disabled due to conflict with common/system.nix

  # Audio is configured in Machines/lenovo-legion-16irx8h/drivers/realtek-audio.nix

  # Dual-boot support services (from /etc/nixos)
  services.udisks2.enable = true;         # Auto-mounting support
  services.timesyncd.enable = true;       # Network time sync (important for dual-boot)
  services.fstrim.enable = true;          # SSD optimization

  # Allow unfree packages for nvidia and other proprietary software
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile
  environment.systemPackages = with pkgs; [
    helix
    btop
    fastfetch
    mc
    git
    hyprland
    # slack is now provided by common/electron-apps.nix
    # Boot and partition management tools
    efibootmgr      # EFI boot entry management
    gparted         # Graphical partition editor
    ntfs3g          # NTFS filesystem support
    os-prober       # Detect other operating systems
    # File system tools
    dosfstools      # FAT/FAT32 tools
    parted          # Command line partitioning
  ];

  # Enable zram with 15% of RAM
  zramSwap = {
    enable = true;
    memoryPercent = 15;
  };

  # Service to load current system into RAM (adapted from yoga)
  systemd.services.nix-system-ram = {
    description = "Load current system closure into RAM";
    wantedBy = [ "multi-user.target" ];
    after = [ "local-fs.target" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "cache-system" ''
        # Cache current system
        ${pkgs.vmtouch}/bin/vmtouch -dl $(readlink -f /run/current-system)

        # Also cache current user profile
        ${pkgs.vmtouch}/bin/vmtouch -dl /nix/var/nix/profiles/per-user/logger/profile

        # Cache frequently used applications
        ${pkgs.vmtouch}/bin/vmtouch -dl /nix/store/*-firefox-*
        ${pkgs.vmtouch}/bin/vmtouch -dl /nix/store/*-warp-terminal-*

        # Report status
        echo "Current system closure size:"
        ${pkgs.nix}/bin/nix path-info -Sh /run/current-system
      '';
      ExecStop = pkgs.writeShellScript "uncache-system" ''
        ${pkgs.vmtouch}/bin/vmtouch -e $(readlink -f /run/current-system)
        ${pkgs.vmtouch}/bin/vmtouch -e /nix/var/nix/profiles/per-user/logger/profile
        ${pkgs.vmtouch}/bin/vmtouch -e /nix/store/*-firefox-*
        ${pkgs.vmtouch}/bin/vmtouch -e /nix/store/*-warp-terminal-*
      '';

      MemoryMax = "16G";
      Restart = "no";
      TimeoutStartSec = "5m";
    };
  };

  # Properly disable the auto-generated timer for nix-system-ram
  # The service runs once at boot via wantedBy, no timer needed
  systemd.timers.nix-system-ram = {
    enable = false;
    # Ensure timer unit is properly defined but disabled
    timerConfig = {};
  };

  # system.stateVersion = "25.05"; # Commented due to conflict with common/system.nix
}
